package io.github.rockerhieu.emojicon.util;

import java.util.HashMap;
import java.util.Map;

import io.github.rockerhieu.emojicon.R;

public class EmotionHelper {
	public final static Map<String, Integer> EmotionRule = new HashMap<String, Integer>() {
		{
			//w_default
			put("[最右]", R.drawable.d_zuiyou);
			put("[微笑]", R.drawable.d_hehe);
			put("[嘻嘻]", R.drawable.d_xixi);
			put("[哈哈]", R.drawable.d_haha);
			put("[爱你]", R.drawable.d_aini);
			put("[愛你]", R.drawable.d_aini);
			put("[挖鼻]", R.drawable.d_wabishi);
			put("[挖鼻]", R.drawable.d_wabishi);
			put("[吃惊]", R.drawable.d_chijing);
			put("[吃驚]", R.drawable.d_chijing);
			put("[晕]", R.drawable.d_yun);
			put("[暈]", R.drawable.d_yun);
			put("[泪]", R.drawable.d_lei);
			put("[淚]", R.drawable.d_lei);
			put("[馋嘴]", R.drawable.d_chanzui);
			put("[饞嘴]", R.drawable.d_chanzui);
			put("[抓狂]", R.drawable.d_zhuakuang);
			put("[抓狂]", R.drawable.d_zhuakuang);
			put("[哼]", R.drawable.d_heng);
			put("[哼]", R.drawable.d_heng);
			put("[可爱]", R.drawable.d_keai);
			put("[可愛]", R.drawable.d_keai);
			put("[怒]", R.drawable.d_nu);
			put("[怒]", R.drawable.d_nu);
			put("[汗]", R.drawable.d_han);
			put("[汗]", R.drawable.d_han);
			put("[害羞]", R.drawable.d_haixiu);
			put("[害羞]", R.drawable.d_haixiu);
			put("[睡]", R.drawable.d_shuijiao);
			put("[睡]", R.drawable.d_shuijiao);
			put("[钱]", R.drawable.d_qian);
			put("[錢]", R.drawable.d_qian);
			put("[偷笑]", R.drawable.d_touxiao);
			put("[偷笑]", R.drawable.d_touxiao);
			put("[笑cry]", R.drawable.d_xiaoku);
			put("[doge]", R.drawable.d_doge);
			put("[doge]", R.drawable.d_doge);
			put("[喵喵]", R.drawable.d_miao);
			put("[喵喵]", R.drawable.d_miao);
			put("[酷]", R.drawable.d_ku);
			put("[酷]", R.drawable.d_ku);
			put("[衰]", R.drawable.d_shuai);
			put("[衰]", R.drawable.d_shuai);
			put("[闭嘴]", R.drawable.d_bizui);
			put("[閉嘴]", R.drawable.d_bizui);
			put("[鄙视]", R.drawable.d_bishi);
			put("[鄙視]", R.drawable.d_bishi);
			put("[色]", R.drawable.d_huaxin);
			put("[色]", R.drawable.d_huaxin);
			put("[鼓掌]", R.drawable.d_guzhang);
			put("[鼓掌]", R.drawable.d_guzhang);
			put("[悲伤]", R.drawable.d_beishang);
			put("[悲傷]", R.drawable.d_beishang);
			put("[思考]", R.drawable.d_sikao);
			put("[思考]", R.drawable.d_sikao);
			put("[生病]", R.drawable.d_shengbing);
			put("[生病]", R.drawable.d_shengbing);
			put("[亲亲]", R.drawable.d_qinqin);
			put("[親親]", R.drawable.d_qinqin);
			put("[怒骂]", R.drawable.d_numa);
			put("[怒罵]", R.drawable.d_numa);
			put("[太开心]", R.drawable.d_taikaixin);
			put("[太開心]", R.drawable.d_taikaixin);
			put("[白眼]", R.drawable.d_landelini);
			put("[白眼]", R.drawable.d_landelini);
			put("[右哼哼]", R.drawable.d_youhengheng);
			put("[右哼哼]", R.drawable.d_youhengheng);
			put("[左哼哼]", R.drawable.d_zuohengheng);
			put("[左哼哼]", R.drawable.d_zuohengheng);
			put("[嘘]", R.drawable.d_xu);
			put("[嘘]", R.drawable.d_xu);
			put("[委屈]", R.drawable.d_weiqu);
			put("[委屈]", R.drawable.d_weiqu);
			put("[吐]", R.drawable.d_tu);
			put("[吐]", R.drawable.d_tu);
			put("[可怜]", R.drawable.d_kelian);
			put("[可憐]", R.drawable.d_kelian);
			put("[哈欠]", R.drawable.d_dahaqi);
			put("[哈欠]", R.drawable.d_dahaqi);
			put("[挤眼]", R.drawable.d_jiyan);
			put("[擠眼]", R.drawable.d_jiyan);
			put("[失望]", R.drawable.d_shiwang);
			put("[失望]", R.drawable.d_shiwang);
			put("[顶]", R.drawable.d_ding);
			put("[頂]", R.drawable.d_ding);
			put("[疑问]", R.drawable.d_yiwen);
			put("[疑問]", R.drawable.d_yiwen);
			put("[困]", R.drawable.d_kun);
			put("[困]", R.drawable.d_kun);
			put("[感冒]", R.drawable.d_ganmao);
			put("[感冒]", R.drawable.d_ganmao);
			put("[拜拜]", R.drawable.d_baibai);
			put("[拜拜]", R.drawable.d_baibai);
			put("[黑线]", R.drawable.d_heixian);
			put("[黑線]", R.drawable.d_heixian);
			put("[阴险]", R.drawable.d_yinxian);
			put("[阴险]", R.drawable.d_yinxian);
			put("[打脸]", R.drawable.d_dalian);
			put("[打臉]", R.drawable.d_dalian);
			put("[傻眼]", R.drawable.d_shayan);
			put("[傻眼]", R.drawable.d_shayan);
			put("[互粉]", R.drawable.f_hufen);
			put("[互粉]", R.drawable.f_hufen);
			put("[心]", R.drawable.l_xin);
			put("[心]", R.drawable.l_xin);
			put("[伤心]", R.drawable.l_shangxin);
			put("[傷心]", R.drawable.l_shangxin);
			put("[猪头]", R.drawable.d_zhutou);
			put("[豬頭]", R.drawable.d_zhutou);
			put("[熊猫]", R.drawable.d_xiongmao);
			put("[熊貓]", R.drawable.d_xiongmao);
			put("[兔子]", R.drawable.d_tuzi);
			put("[兔子]", R.drawable.d_tuzi);
			put("[握手]", R.drawable.h_woshou);
			put("[握手]", R.drawable.h_woshou);
			put("[作揖]", R.drawable.h_zuoyi);
			put("[作揖]", R.drawable.h_zuoyi);
			put("[赞]", R.drawable.h_zan);
			put("[贊]", R.drawable.h_zan);
			put("[耶]", R.drawable.h_ye);
			put("[耶]", R.drawable.h_ye);
			put("[good]", R.drawable.h_good);
			put("[good]", R.drawable.h_good);
			put("[弱]", R.drawable.h_ruo);
			put("[弱]", R.drawable.h_ruo);
			put("[NO]", R.drawable.h_buyao);
			put("[NO]", R.drawable.h_buyao);
			put("[ok]", R.drawable.h_ok);
			put("[ok]", R.drawable.h_ok);
			put("[haha]", R.drawable.h_haha);
			put("[haha]", R.drawable.h_haha);
			put("[来]", R.drawable.h_lai);
			put("[來]", R.drawable.h_lai);
			put("[拳头]", R.drawable.h_quantou);
			put("[拳頭]", R.drawable.h_quantou);
			put("[威武]", R.drawable.f_v5);
			put("[威武]", R.drawable.f_v5);
			put("[鲜花]", R.drawable.w_xianhua);
			put("[鮮花]", R.drawable.w_xianhua);
			put("[钟]", R.drawable.o_zhong);
			put("[鐘]", R.drawable.o_zhong);
			put("[浮云]", R.drawable.w_fuyun);
			put("[浮雲]", R.drawable.w_fuyun);
			put("[飞机]", R.drawable.o_feiji);
			put("[飛機]", R.drawable.o_feiji);
			put("[月亮]", R.drawable.w_yueliang);
			put("[月亮]", R.drawable.w_yueliang);
			put("[太阳]", R.drawable.w_taiyang);
			put("[太陽]", R.drawable.w_taiyang);
			put("[微风]", R.drawable.w_weifeng);
			put("[微風]", R.drawable.w_weifeng);
			put("[下雨]", R.drawable.w_xiayu);
			put("[下雨]", R.drawable.w_xiayu);
			put("[给力]", R.drawable.f_geili);
			put("[給力]", R.drawable.f_geili);
			put("[神马]", R.drawable.f_shenma);
			put("[神馬]", R.drawable.f_shenma);
			put("[围观]", R.drawable.o_weiguan);
			put("[圍觀]", R.drawable.o_weiguan);
			put("[话筒]", R.drawable.o_huatong);
			put("[話筒]", R.drawable.o_huatong);
			put("[奥特曼]", R.drawable.d_aoteman);
			put("[奥特曼]", R.drawable.d_aoteman);
			put("[草泥马]", R.drawable.d_shenshou);
			put("[草泥馬]", R.drawable.d_shenshou);
			put("[萌]", R.drawable.f_meng);
			put("[萌]", R.drawable.f_meng);
			put("[囧]", R.drawable.f_jiong);
			put("[囧]", R.drawable.f_jiong);
			put("[织]", R.drawable.f_zhi);
			put("[織]", R.drawable.f_zhi);
			put("[礼物]", R.drawable.o_liwu);
			put("[禮物]", R.drawable.o_liwu);
			put("[喜]", R.drawable.f_xi);
			put("[喜]", R.drawable.f_xi);
			put("[围脖]", R.drawable.o_weibo);
			put("[圍脖]", R.drawable.o_weibo);
			put("[音乐]", R.drawable.o_yinyue);
			put("[音樂]", R.drawable.o_yinyue);
			put("[绿丝带]", R.drawable.o_lvsidai);
			put("[綠絲帶]", R.drawable.o_lvsidai);
			put("[蛋糕]", R.drawable.o_dangao);
			put("[蛋糕]", R.drawable.o_dangao);
			put("[蜡烛]", R.drawable.o_lazhu);
			put("[蠟燭]", R.drawable.o_lazhu);
			put("[干杯]", R.drawable.o_ganbei);
			put("[乾杯]", R.drawable.o_ganbei);
			put("[男孩儿]", R.drawable.d_nanhaier);
			put("[男孩儿]", R.drawable.d_nanhaier);
			put("[女孩儿]", R.drawable.d_nvhaier);
			put("[女孩儿]", R.drawable.d_nvhaier);
			put("[肥皂]", R.drawable.d_feizao);
			put("[肥皂]", R.drawable.d_feizao);
			put("[照相机]", R.drawable.o_zhaoxiangji);
			put("[照相机]", R.drawable.o_zhaoxiangji);
			put("[浪]", R.drawable.d_lang);
			put("[浪]", R.drawable.d_lang);
			put("[沙尘暴]", R.drawable.w_shachenbao);
			put("[沙塵暴]", R.drawable.w_shachenbao);
			//lhh
			put("[笑哈哈]", R.drawable.lxh_xiaohaha);
			put("[笑哈哈]",R.drawable.lxh_xiaohaha);
			put("[好爱哦]",R.drawable.lxh_haoaio);
			put("[好愛哦]",R.drawable.lxh_haoaio);
			put("[噢耶]",R.drawable.lxh_oye);
			put("[噢耶]",R.drawable.lxh_oye);
			put("[偷乐]",R.drawable.lxh_toule);
			put("[偷樂]",R.drawable.lxh_toule);
			put("[泪流满面]",R.drawable.lxh_leiliumanmian);
			put("[淚流滿面]",R.drawable.lxh_leiliumanmian);
			put("[巨汗]",R.drawable.lxh_juhan);
			put("[巨汗]",R.drawable.lxh_juhan);
			put("[抠鼻屎]",R.drawable.lxh_koubishi);
			put("[摳鼻屎]",R.drawable.lxh_koubishi);
			put("[求关注]",R.drawable.lxh_qiuguanzhu);
			put("[求關注]",R.drawable.lxh_qiuguanzhu);
			put("[好喜欢]",R.drawable.lxh_haoxihuan);
			put("[好喜歡]",R.drawable.lxh_haoxihuan);
			put("[崩溃]",R.drawable.lxh_bengkui);
			put("[崩潰]",R.drawable.lxh_bengkui);
			put("[好囧]",R.drawable.lxh_haojiong);
			put("[好冏]",R.drawable.lxh_haojiong);
			put("[震惊]",R.drawable.lxh_zhenjing);
			put("[震驚]",R.drawable.lxh_zhenjing);
			put("[别烦我]",R.drawable.lxh_biefanwo);
			put("[別煩我]",R.drawable.lxh_biefanwo);
			put("[不好意思]",R.drawable.lxh_buhaoyisi);
			put("[不好意思]",R.drawable.lxh_buhaoyisi);
			put("[羞嗒嗒]",R.drawable.lxh_xiudada);
			put("[羞嗒嗒]",R.drawable.lxh_xiudada);
			put("[得意地笑]",R.drawable.lxh_deyidexiao);
			put("[得意地笑]",R.drawable.lxh_deyidexiao);
			put("[纠结]",R.drawable.lxh_jiujie);
			put("[糾結]",R.drawable.lxh_jiujie);
			put("[给劲]",R.drawable.lxh_geijin);
			put("[給勁]",R.drawable.lxh_geijin);
			put("[悲催]",R.drawable.lxh_beicui);
			put("[悲催]",R.drawable.lxh_beicui);
			put("[甩甩手]",R.drawable.lxh_shuaishuaishou);
			put("[甩甩手]",R.drawable.lxh_shuaishuaishou);
			put("[好棒]",R.drawable.lxh_haobang);
			put("[好棒]",R.drawable.lxh_haobang);
			put("[瞧瞧]",R.drawable.lxh_qiaoqiao);
			put("[瞧瞧]",R.drawable.lxh_qiaoqiao);
			put("[不想上班]",R.drawable.lxh_buxiangshangban);
			put("[不想上班]",R.drawable.lxh_buxiangshangban);
			put("[困死了]",R.drawable.lxh_kunsile);
			put("[困死了]",R.drawable.lxh_kunsile);
			put("[许愿]",R.drawable.lxh_xuyuan);
			put("[許願]",R.drawable.lxh_xuyuan);
			put("[丘比特]",R.drawable.lxh_qiubite);
			put("[丘比特]",R.drawable.lxh_qiubite);
			put("[有鸭梨]",R.drawable.lxh_youyali);
			put("[有鴨梨]",R.drawable.lxh_youyali);
			put("[想一想]",R.drawable.lxh_xiangyixiang);
			put("[想一想]",R.drawable.lxh_xiangyixiang);
			put("[躁狂症]",R.drawable.lxh_zaokuangzheng);
			put("[躁狂症]",R.drawable.lxh_zaokuangzheng);
			put("[转发]",R.drawable.lxh_zhuanfa);
			put("[轉發]",R.drawable.lxh_zhuanfa);
			put("[互相膜拜]",R.drawable.lxh_xianghumobai);
			put("[互相膜拜]",R.drawable.lxh_xianghumobai);
			put("[雷锋]",R.drawable.lxh_leifeng);
			put("[雷鋒]",R.drawable.lxh_leifeng);
			put("[杰克逊]",R.drawable.lxh_jiekexun);
			put("[傑克遜]",R.drawable.lxh_jiekexun);
			put("[玫瑰]",R.drawable.lxh_meigui);
			put("[玫瑰]",R.drawable.lxh_meigui);
			put("[hold住]",R.drawable.lxh_holdzhu);
			put("[hold住]",R.drawable.lxh_holdzhu);
			put("[群体围观]",R.drawable.lxh_quntiweiguan);
			put("[群體圍觀]",R.drawable.lxh_quntiweiguan);
			put("[推荐]",R.drawable.lxh_tuijian);
			put("[推薦]",R.drawable.lxh_tuijian);
			put("[赞啊]",R.drawable.lxh_zana);
			put("[贊啊]",R.drawable.lxh_zana);
			put("[被电]",R.drawable.lxh_beidian);
			put("[被電]",R.drawable.lxh_beidian);
			put("[霹雳]",R.drawable.lxh_pili);
			put("[霹靂]",R.drawable.lxh_pili);
		}
	};
}
